### ISSUE TITLE
Backup never completes.

### ISSUE THREAD

**Issue by fmc000** [redromnon/iBackep#3]
I started using iBackep today -under Fedora 39 ( usbmuxd-1.1.1^20230720git61b99ab-1.fc39.x86_64 - libimobiledevice-1.3.0^20230705git6fc41f5-1.fc39.x86_64 - libimobiledevice-utils-1.3.0^20230705git6fc41f5-1.fc39.x86_64 ). My device is an iPhone SE 2020 running iOS 17.0.3 .

The device is recognized, the backup starts and runs for a while then stops with:

Exception in thread Thread-26 (do_backup):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "ui/app.py", line 130, in do_backup
  File "ui/operations.py", line 51, in backup
  File "flet/control.py", line 259, in update
  File "flet/page.py", line 197, in update
  File "flet/page.py", line 213, in __update
  File "flet/connection.py", line 104, in send_commands
  File "flet/connection.py", line 119, in _send_message_with_result
  File "flet/reconnecting_websocket.py", line 73, in send
  File "websocket/_app.py", line 234, in send
  File "websocket/_core.py", line 283, in send
  File "websocket/_core.py", line 311, in send_frame
  File "websocket/_core.py", line 525, in _send
  File "websocket/_socket.py", line 170, in send
  File "websocket/_socket.py", line 147, in _send
ConnectionResetError: [Errno 104] Connection reset by peer

After the crash the spinning icon on the iPhone is still there and disappears only when I disconnect the cable.

Relevant dmesg entries:

[20800.694028] usb 3-1: new high-speed USB device number 10 using xhci_hcd
[20800.823710] usb 3-1: New USB device found, idVendor=05ac, idProduct=12a8, bcdDevice=12.08
[20800.823720] usb 3-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[20800.823723] usb 3-1: Product: iPhone
[20800.823725] usb 3-1: Manufacturer: Apple Inc.
[20800.823728] usb 3-1: SerialNumber: <obscured>
[20800.907026] ipheth 3-1:4.2: ipheth_enable_ncm: usb_control_msg: 0
[20800.907473] ipheth 3-1:4.2: Apple iPhone USB Ethernet device attached
[20800.909977] ipheth 3-1:4.2 enp0s20f0u1c4i2: renamed from eth0
[21268.793928] apple-mfi-fastcharge 3-1: USB disconnect, device number 10
[21268.804899] ipheth 3-1:4.2: Apple iPhone USB Ethernet now disconnected

Please let me know how to help debug this issue, thank you.

**Comment by redromnon** [comment]
Although I cannot replicate the exact same error, I am experiencing a similar issue myself. I too own an iPhone SE 2020 running on iOS 17.0.3.

The progress bar keeps getting stuck at 97% after which my iPhone doesn't show the spinning icon anymore. Maybe it was successfully completed? If I use `idevicebackup2` via the command-line, it works just fine.

I will need to look into this.

**Comment by redromnon** [comment]
Moreover, the log that you've pasted tells me that there is an issue with how Flet is handling the backup process. Nothing wrong with `libimobiledevice`

**Comment by fmc000** [comment]
Indeed the backup works fine with the command line utilities, that's what I normally use. I was just trying this GUI but it looks like I'm not the only one with this problem.

**Comment by redromnon** [comment]
The new release should solve this issue.

**Comment by fmc000** [comment]
Unfortunately the new release doesn't even start as it needs libmpv.so.1 which is obsolete as now mpv provides libmpv.so.2 .


```
 ⤷ $ ./ibackep 
[obscured $HOME]/.flet/bin/flet-0.21.2/flet/flet: error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory
```

**Comment by redromnon** [comment]
Hmmm, looks like that's a dependency required by Flet. I've got to downgrade the Flet version.

**Comment by fmc000** [comment]
Yes, it's strange that it depends on an obsolete version of mpv.

**Comment by redromnon** [comment]
I'm use Pop OS 22.04 so I don't encounter this error. Maybe newer releases don't use mpv 1

**Comment by redromnon** [comment]
Hopefully, the new fix I've released should work on all distros. Downgraded Flet to 0.0.19, because the newer ones have a `Video` controller that needs `libmpv`.

**Comment by fmc000** [comment]
Now the app starts but it's still not working. Pressing the folder icon does nothing here.

On the terminal there are a few error messages:

```
 ⤷ $ ./ibackep 

(flet:2672): Gdk-CRITICAL **: 08:03:49.223: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed

** (flet:2672): CRITICAL **: 08:03:49.278: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (flet:2672): CRITICAL **: 08:03:49.278: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (flet:2672): CRITICAL **: 08:03:49.279: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (flet:2672): CRITICAL **: 08:03:49.279: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (flet:2672): CRITICAL **: 08:03:49.279: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found
```
I use KDE Plasma 6.0.4 on Archlinux. I also found these errors in the journal:

```
mag 13 08:10:19 tu45b-arch xdg-desktop-portal-kde[1696]: xdp-kde-settings: Namespace  "org.gnome.desktop.interface"  is not supported
mag 13 08:10:19 tu45b-arch xdg-desktop-portal-kde[1696]: xdp-kde-settings: Namespace  "org.gnome.desktop.interface"  is not supported
mag 13 08:10:19 tu45b-arch xdg-desktop-portal-kde[1696]: xdp-kde-settings: Namespace  "org.gnome.desktop.interface"  is not supported
mag 13 08:10:19 tu45b-arch xdg-desktop-portal-kde[1696]: xdp-kde-settings: Namespace  "org.gnome.desktop.a11y.interface"  is not supported
mag 13 08:10:19 tu45b-arch xdg-desktop-portal-kde[1696]: xdp-kde-settings: Namespace  "org.gnome.desktop.interface"  is not supported
mag 13 08:10:19 tu45b-arch kwin_wayland[1462]: kwin_core: Cannot grant a token to KWin::ClientConnection(0x63127f429d50)
```

**Comment by redromnon** [comment]
It works fine on Ubuntu 24 and Pop OS 22 GNOME. Is it a desktop environment specific-issue? You're not alone, as indicated in this issue: https://github.com/flet-dev/flet/issues/1134

**Comment by fmc000** [comment]
Maybe something like this?

https://github.com/synfig/synfig/pull/1262/commits/8415dcc7cbbb485ca1920ad89c8d1d26afdb81a7

My system has 3.24 so maybe it is something that started with 3.22 .

**Comment by redromnon** [comment]
Didn't you try this program on Fedora? Do you still have access to it to check if this issue occurs there too?

**Comment by fmc000** [comment]
I very briefly used Fedora but I almost immediately went back to Arch. I
have only one laptop, sorry.

Anyways, it looks like this "Flet" thing is very picky on which environment is running in. I tried to circumvent the libmpv error by symlinking the new libmpv.so.2.3.0 as libmpv.so.1 and not Flet is complaining about the openssl, glibc and GCC versions. 

```
./.flet/bin/flet-0.21.2/flet/flet: /tmp/_MEIpXXoUy/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /usr/lib/librubberband.so.2)
./.flet/bin/flet-0.21.2/flet/flet: /tmp/_MEIpXXoUy/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /usr/lib/libopenmpt.so.0)
./.flet/bin/flet-0.21.2/flet/flet: /tmp/_MEIpXXoUy/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /usr/lib/libsrt.so.1.5)
./.flet/bin/flet-0.21.2/flet/flet: /tmp/_MEIpXXoUy/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /usr/lib/libshaderc_shared.so.1)
./.flet/bin/flet-0.21.2/flet/flet: /tmp/_MEIpXXoUy/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /usr/lib/libSPIRV.so.14)
./.flet/bin/flet-0.21.2/flet/flet: /tmp/_MEIpXXoUy/libssl.so.3: version `OPENSSL_3.2.0' not found (required by /usr/lib/libcurl.so.4)
./.flet/bin/flet-0.21.2/flet/flet: /tmp/_MEIpXXoUy/libgcc_s.so.1: version `GCC_13.0.0' not found (required by /usr/lib/libhwy.so.1)
./.flet/bin/flet-0.21.2/flet/flet: /tmp/_MEIpXXoUy/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /usr/lib/libSPIRV-Tools.so)
./.flet/bin/flet-0.21.2/flet/flet: /tmp/_MEIpXXoUy/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /usr/lib/libSPIRV-Tools-opt.so)
```

**Comment by redromnon** [comment]
So, I don't know if the newer version of Flet (GUI framework used) solves this issue. What's more surprising is that it's using `flet-0.21.2` instead of `flet-0.19.0` which I downgraded it to.

**Comment by fmc000** [comment]
Sorry, I had to be more clear. I'm trying both releases and I found that the 0.19 is not running with the current GTK3 release and 0.21 is not running with the current mpv release.

**Comment by redromnon** [comment]
At this point, I'm unsure what to do.

**Comment by fmc000** [comment]
I'd just close this issue as in your case the backup ends correctly. As for me I'm trying pymobiledevice3 directly. Thanks for your help anyways.

**Comment by redromnon** [comment]
Much appreciated.

**Comment by redromnon** [comment]
So I tried replicating this issue on my Kubuntu VM and yeah, I get the same issue and error: `xdp-kde-settings: Namespace  "org.gnome.desktop.interface"  is not supported`.
I also installed `zenity` since it is pre-requisite for Flet on Linux.

Is Flet trying to open GNOME's file picker?

**Comment by fmc000** [comment]
I simply don't know. I tried stracing the process but I got an 11MB file just to press the button and flet forks 54 processes just to start your app so I really don't know what to do.

The only thing I can say for sure is that this "flet" thing is not really designed to be DE-agnostic as your test proved that this is not a KDE failure (Kubuntu ships with Plasma 5 and Arch rolls Plasma 6 - flet does not work with any of them).

**Comment by redromnon** [comment]
I'll try to create an issue on the Flet repo. Let's wait and see.

**Comment by redromnon** [comment]
I'm now using `zenity` to handle the backup folder selection. Tested it on both Kubuntu and PopOS. 
Hopefully this irritating issue gets resolved for all users.

**Comment by fmc000** [comment]
I'm sorry to report that it still doesn't work on Arch. I get the message:

`Looks like Zenity is not installed`

even if it actually is:

```
 ⤷ $ pacman -Q zenity
zenity 4.0.1-1
```

**Comment by redromnon** [comment]
Can you run zenity --version and check?

**Comment by fmc000** [comment]
It should have been clear from my previous message:

```
 ⤷ $ zenity --version
4.0.1
```

**Comment by redromnon** [comment]
I just wanted to double-check by running `zenity --version` directly rather than `pacman -Q zenity`
Because ibackep runs the above command to verify if zenity is installed.

**Comment by redromnon** [comment]
Ugh, I really need to set up GitHub actions now to automate builds for changes. 
Anyway, I've replaced the v2.0.2's executable with a new one. I've now used `is returncode = 0` as a more robust checking method. Has to work now.

**Comment by fmc000** [comment]
Sorry, no changes.

**Comment by redromnon** [comment]
I need to dig deeper. Need to test it on an Arch VM.

**Comment by fmc000** [comment]
If you need a tester, I'm here. Anyways, this strace output may help:

`[pid  5767] writev(2, [{iov_base="/bin/sh", iov_len=7}, {iov_base=": ", iov_len=2}, {iov_base="symbol lookup error", iov_len=19}, {iov_base=": ", iov_len=2}, {iov_base="/bin/sh", iov_len=7}, {iov_base=": ", iov_len=2}, {iov_base="undefined symbol: rl_trim_arg_fr"..., iov_len=41}, {iov_base="", iov_len=0}, {iov_base="", iov_len=0}, {iov_base="\n", iov_len=1}], 10) = 81`

PID 5767 is forked by ibackup when running 

`/bin/sh -c "zenity --version"`

relevant bugs on github:

`https://github.com/conda-forge/readline-feedstock/issues/28`
`https://github.com/badabing2005/PixelFlasher/issues/130`

```
 ⤷ $ bash --version|head -1
GNU bash, version 5.2.26(1)-release (x86_64-pc-linux-gnu)
```

I can confirm that the readline library included in ibackep does not contain that symbol:

```
 ⤷ $ strings /tmp/_MEITpHJIQ/libreadline.so.8 |grep rl-trim_arg
 ⤷ $ 
```

whilst the Arch-provided does:

```
 ⤷ $ strings /usr/lib/libreadline.so|grep rl_trim_arg
rl_trim_arg_from_keyseq
 ⤷ $ 
```

**Comment by redromnon** [comment]
I'm closing this issue in favour of #6 
Let's continue this discussion there.
